// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr_mz42P9SxCthkzj3d_WhraQqVNC2YPI',
    appId: '1:709902469934:web:f464e76dbb2243348b88bf',
    messagingSenderId: '709902469934',
    projectId: 'projetmobile-cd874',
    authDomain: 'projetmobile-cd874.firebaseapp.com',
    storageBucket: 'projetmobile-cd874.firebasestorage.app',
    measurementId: 'G-6VGDPH8JX8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMDaUF-GRPr6Y3jFATyBrRaohNEWEKONE',
    appId: '1:709902469934:android:510dfc6fe0c7b6528b88bf',
    messagingSenderId: '709902469934',
    projectId: 'projetmobile-cd874',
    storageBucket: 'projetmobile-cd874.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSqENz7x71TQWLqg2QPUR8b-N-Oq27zIc',
    appId: '1:709902469934:ios:ba43e813a33abf138b88bf',
    messagingSenderId: '709902469934',
    projectId: 'projetmobile-cd874',
    storageBucket: 'projetmobile-cd874.firebasestorage.app',
    iosBundleId: 'com.example.miniProjet',
  );

}